dataset_path: path/to/lenta-ru-news.csv
sequence_len: 256

dev_mode: True # Load only part of the dataset
chunk_size: 50000 # Part size
accelerator: "gpu"

model: "base_punctuator"
encoder: "cointegrated/rubert-tiny2" # sberbank-ai/ruRoberta-large cointegrated/rubert-tiny2 DeepPavlov/rubert-base-cased
augment_rate: 0.2
ckpt_path: checkpoints/path/to/checkpoint.ckpt
continue_from_ckpt: false
epochs: 50
batch_size: 64
num_workers: 1
log_every_n_step: 10
val_check_interval: 1.0

wandb:
    project: "punctuation_restoration"
    name: "as_model" # if 'as_model' then name will be taken from 'model' parameter
    mode: "online" # online or disabled

seed: 42
